const swaggerAutogen = require("swagger-autogen")();

const outputFile = "./swagger.json";
// const endpointsFiles = ['./routes/places-routes.js', './routes/users-routes.js']
const endpointsFiles = ["./app.js"];

const doc = {
  info: {
    version: "1.0.1",
    title: "REST API of MERN Project",
    description:
      "Documentation automatically generated by the <b>swagger-autogen</b> module.",
  },
  host: "localhost:5000",
  basePath: "/",
  schemes: "http",
  tags: [
    {
      name: "Users",
      description: "Endpoint of Users",
    },
    {
      name: "Places",
      description: "Endpoint of Places",
    },
  ],

  definitions: {
    Users: {
      name: "Jhon Doe",
      email: "test@gmail.com",
      password: "test12pass",
      places: ["idPlace1", "idPlace2"]
    },
    Places: {
      title: "Empire state building",
      description: "One of the most famous sky scrapers in the world!",
      location: {
        lat: 40.7484474,
        lng: -73.9878584,
      },
      address: "20 W 34th St, New York, NY 10001, Estados Unidos",
      creator: "u1",
    },
    loginUser: {
      $email: "YOUR_EMAIL@something.com",
      $password: "YOUR_PASSWORD",
    },
    signup: {
      $name: "Jhon Doe",
      $email: "YOUR_EMAIL@something.com",
      $password: "YOUR_PASSWORD",
    },
    createPlace: {
      $title: "Title of a Place",
      $description: "Description of location",
      $address: "Complete address of a Place",
      $creator: "Creator name"
    },
    patchPlace: {
      $title: "New title of a Place",
      $description: "New description of a Place"
    }
  },
};

swaggerAutogen(outputFile, endpointsFiles, doc);
